# Site settings
title: "A ATM 500: Atmospheric Dynamics"
email: brose@albany.edu
description: > # this means to ignore newlines until "baseurl:"
  Class website for A ATM 500, Fall 2015
baseurl: "/facstaff/brose/classes/ATM500_Fall2015" # the subpath of your site, e.g. /blog
url: "http://www.atmos.albany.edu/facstaff/brose/classes/ATM500_Fall2015" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]